// Generated by CoffeeScript 2.3.1
(function() {
  'use strict';
  var CLIPBOARD, CND, CP, alert, badge, debug, echo, help, info, is_tty, log, rpr, urge, warn, whisper;

  //###########################################################################################################
  CND = require('cnd');

  rpr = CND.rpr;

  badge = 'INTERFLUG/main';

  log = CND.get_logger('plain', badge);

  debug = CND.get_logger('debug', badge);

  info = CND.get_logger('info', badge);

  warn = CND.get_logger('warn', badge);

  alert = CND.get_logger('alert', badge);

  help = CND.get_logger('help', badge);

  urge = CND.get_logger('urge', badge);

  whisper = CND.get_logger('whisper', badge);

  echo = CND.echo.bind(CND);

  //...........................................................................................................
  CLIPBOARD = require('clipboardy');

  CP = require('child_process');

  //...........................................................................................................
  is_tty = process.stdout.isTTY;

  //-----------------------------------------------------------------------------------------------------------
  this.new = function() {
    var R;
    return R = {
      '~isa': 'INTERFLUG/state',
      windows: {
        self: null,
        target: null
      }
    };
  };

  //-----------------------------------------------------------------------------------------------------------
  this.copy = function(S, text) {
    CLIPBOARD.write(text.toString());
    return null;
  };

  //-----------------------------------------------------------------------------------------------------------
  this.send_text = function(S, text = null) {
    var command;
    if (text != null) {
      this.copy(text);
    }
    // command = """wmctrl -a Sublime && xte 'usleep 250000' 'keydown Control_L' 'key v' 'keyup Control_L'"""
    command = "wmctrl -i -a 0x06c00001 && xte 'usleep 250000' 'keydown Control_L' 'key v' 'keyup Control_L' && wmctrl -i -a 0x05000005";
    CP.execSync(command);
    return null;
  };

  //-----------------------------------------------------------------------------------------------------------
  this.switch_to_window_by_id = function(id) {
    var command, message;
    command = `wmctrl -i -a ${id}`;
    message = CP.execSync(command, {
      encoding: 'utf-8'
    });
    return null;
  };

  //-----------------------------------------------------------------------------------------------------------
  this._get_id_of_active_window = function() {
    var command, message;
    command = "wmctrl -v -a :ACTIVE: 2>&1";
    message = CP.execSync(command, {
      encoding: 'utf-8'
    });
    return message.replace(/^.*window:\s*(\S+)\s*$/gs, '$1');
  };

  //-----------------------------------------------------------------------------------------------------------
  this._get_id_of_selected_window = function() {
    var command, message;
    command = "wmctrl -v -a :SELECT: 2>&1";
    message = CP.execSync(command, {
      encoding: 'utf-8'
    });
    return message.replace(/^.*window:\s*(\S+)\s*$/gs, '$1');
  };

  //-----------------------------------------------------------------------------------------------------------
  this.set_window_ids = function(S) {
    if (is_tty) {
      urge("switch to the target window and click into it");
    }
    S.windows.self = this._get_id_of_active_window();
    S.windows.target = this._get_id_of_selected_window();
    return this.switch_to_window_by_id(S.windows.self);
  };

}).call(this);

//# sourceMappingURL=main.js.map
