// Generated by CoffeeScript 2.3.2
(function() {
  'use strict';
  var CLIPBOARD, CND, CP, alert, badge, debug, echo, help, info, is_tty, log, rpr, urge, warn, whisper;

  //###########################################################################################################
  CND = require('cnd');

  rpr = CND.rpr;

  badge = 'INTERFLUG/main';

  log = CND.get_logger('plain', badge);

  debug = CND.get_logger('debug', badge);

  info = CND.get_logger('info', badge);

  warn = CND.get_logger('warn', badge);

  alert = CND.get_logger('alert', badge);

  help = CND.get_logger('help', badge);

  urge = CND.get_logger('urge', badge);

  whisper = CND.get_logger('whisper', badge);

  echo = CND.echo.bind(CND);

  //...........................................................................................................
  CLIPBOARD = require('clipboardy');

  CP = require('child_process');

  //...........................................................................................................
  is_tty = process.stdout.isTTY;

  //-----------------------------------------------------------------------------------------------------------
  this.new = function() {
    var R;
    return R = {
      '~isa': 'INTERFLUG/state',
      command: null,
      windows: {
        self: null,
        target: null
      }
    };
  };

  //-----------------------------------------------------------------------------------------------------------
  this.copy = function(S, text) {
    CLIPBOARD.write(text.toString());
    return null;
  };

  //-----------------------------------------------------------------------------------------------------------
  this.send_text_to_target_window = function(S, text = null) {
    if (text != null) {
      this.copy(S, text);
    }
    S.command = `wmctrl -i -a ${S.windows.target} &&\nxte 'usleep 250000' 'keydown Control_L' 'key v' 'keyup Control_L' &&\nwmctrl -i -a ${S.windows.self}`.replace(/\s+/gs, ' ');
    CP.execSync(S.command);
    return null;
  };

  //-----------------------------------------------------------------------------------------------------------
  this.switch_to_own_window = function(S) {
    return this._switch_to_window_by_id(S, S.windows.self);
  };

  this.switch_to_target_window = function(S) {
    return this._switch_to_window_by_id(S, S.windows.target);
  };

  //-----------------------------------------------------------------------------------------------------------
  this._switch_to_window_by_id = function(S, id) {
    var message;
    S.command = `wmctrl -i -a ${id}`;
    message = CP.execSync(S.command, {
      encoding: 'utf-8'
    });
    return null;
  };

  //-----------------------------------------------------------------------------------------------------------
  this._get_id_of_active_window = function(S) {
    var message;
    S.command = "wmctrl -v -a :ACTIVE: 2>&1";
    message = CP.execSync(S.command, {
      encoding: 'utf-8'
    });
    return message.replace(/^.*window:\s*(\S+)\s*$/gs, '$1');
  };

  //-----------------------------------------------------------------------------------------------------------
  this._get_id_of_selected_window = function(S) {
    var message;
    S.command = "wmctrl -v -a :SELECT: 2>&1";
    message = CP.execSync(S.command, {
      encoding: 'utf-8'
    });
    return message.replace(/^.*window:\s*(\S+)\s*$/gs, '$1');
  };

  //-----------------------------------------------------------------------------------------------------------
  this.set_window_ids = function(S) {
    if (is_tty) {
      urge("switch to the target window and click into it");
    }
    S.windows.self = this._get_id_of_active_window(S);
    S.windows.target = this._get_id_of_selected_window(S);
    return this._switch_to_window_by_id(S, S.windows.self);
  };

}).call(this);

//# sourceMappingURL=main.js.map
