// Generated by CoffeeScript 2.3.2
(function() {
  'use strict';
  var CND, IFL, alert, badge, debug, echo, help, ifl, info, log, rpr, urge, warn, whisper;

  //###########################################################################################################
  CND = require('cnd');

  rpr = CND.rpr;

  badge = 'INTERFLUG/main';

  log = CND.get_logger('plain', badge);

  debug = CND.get_logger('debug', badge);

  info = CND.get_logger('info', badge);

  warn = CND.get_logger('warn', badge);

  alert = CND.get_logger('alert', badge);

  help = CND.get_logger('help', badge);

  urge = CND.get_logger('urge', badge);

  whisper = CND.get_logger('whisper', badge);

  echo = CND.echo.bind(CND);

  //...........................................................................................................
  IFL = require('../..');

  ifl = IFL.new();

  IFL.set_window_ids(ifl);

  debug(ifl);

}).call(this);

//# sourceMappingURL=demo1.js.map
